### ISSUE TITLE
make error while building cctools

### ISSUE THREAD

**Issue by ipfans** [javacom/toolchain4#10]
the building process said that:

make: **\* No rule to make target `clean'.  Stop.

cat /toolchain4/bld/cctools-iphone/make.log:

make: **\* No targets specified and no makefile found.  Stop.

**Comment by gravitylow** [comment]
Well, you're actually going to want to give the config.log because that has the actual info on the problem. For me, this was solved by:

$> sudo apt-get install gcc-4.4  g++-4.4  g++-4.4-multilib g++-4.4-multilib
$> sudo rm /usr/bin/g++ /usr/bin/gcc
$> sudo ln -s /usr/bin/gcc-4.4 /usr/bin/gcc
$> sudo ln -s /usr/bin/g++-4.4 /usr/bin/g++

But you won't really know; that "error" could mean tons of things.
